title: The title
name: My Github Pages testing domain
description: I'm testing

minima:
  skin: dark

theme: minima
url: "http://vkuhlmann.github.io"

author: Vincent Kuhlmann
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 